{
  "openapi" : "3.0.3",
  "info" : {
    "title": "Todolist Restful API",
    "version": "1",
    "description": "OpenAI for todolist Restful API",
    "termsOfService": "https://github.com/triatmojo",
    "contact": {
      "name": "Tri Atmojo",
      "email": "tatmojo17@gmail.com",
      "url": "https://github.com/triatmojo"
    },
    "license": {
      "name": "Apache-2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "url": "https://{environment}.alamkoding.com/api/v1",
      "description": "Todolist  Restful API Servers",
      "variables": {
        "environment" : {
          "description": "Server Environment",
          "default": "dev",
          "enum": [
            "dev",
            "qa",
            "prod"
          ]
        }
      }
    }
  ],
  "externalDocs": {
    "description": "Youtube Alamkoding",
    "url": "https://www.youtube.com/c/AlamKoding"
  },
  "paths": {
    "/todolist" : {
      "get": {
        "security": [
          {
            "TodolistAuth" : []
          }
        ],
        "tags": ["Todolist"],
        "summary": "Get all todolist",
        "description": "Get all todolist by default",
        "parameters": [
          {
            "name": "include_done",
            "in": "query",
            "required": false,
            "description": "Is include todolist by default",
            "schema": {
              "type": "boolean",
              "nullable": true,
              "default": false
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "description": "Filter todolist by name",
            "schema": {
              "type": "string",
              "nullable": true,
              "minLength": 1,
              "maxLength": 100
            },
            "examples": {
              "golang" : {
                "description": "Example name Golang",
                "value": "GOLANG"
              },
              "php" : {
                "description": "Example name Php",
                "value": "PHP"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success get all todolist",
            "content": {
              "application/json" : {
                "schema": {
                  "$ref": "#/components/schemas/ArrayTodolist"
                },
                "examples": {
                  "success" : {
                    "description": "Success get all todolist",
                    "value": [
                      {
                        "id" : "1",
                        "name" : "Golang",
                        "priority" : 2,
                        "tags" : [
                          "Golang",
                          "Programmming"
                        ]
                      },
                      {
                        "id" : "2",
                        "name" : "PHP",
                        "priority" : 3,
                        "tags" : [
                          "PHP",
                          "Programmming"
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "TodolistAuth" : []
          }
        ],
        "tags": ["Todolist"],
        "summary": "Create new todolist",
        "description": "Create new todolist to database",
        "requestBody": {
          "required": true,
          "content": {
            "application/json" : {
              "schema": {
                "$ref": "#/components/schemas/Todolist"
              },
              "examples": {
                "golang" : {
                  "description": "Example create todolist Golang",
                  "value": {
                    "name" : "Golang",
                    "priority": 1,
                    "tags" : [
                      "Golang",
                      "Programming"
                    ]
                  }
                },
                "php" : {
                  "description": "Example create todolist PHP",
                  "value": {
                    "name" : "PHP",
                    "priority": 2,
                    "tags" : [
                      "PHP",
                      "Programming"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success create todolist",
            "content": {
              "application/json" : {
                "schema": {
                  "$ref": "#/components/schemas/Todolist"
                },
                "examples": {
                  "Golang" : {
                    "description": "Success create golang todolist",
                    "value":  {
                      "id" : "1",
                      "name" : "Golang",
                      "priority" : 2,
                      "tags" : [
                        "Golang",
                        "Programming"
                      ]
                    }
                  },
                  "PHP" : {
                    "description": "Success create php todolist",
                    "value": {
                      "id" : "2",
                      "name" : "PHP",
                      "priority" : 6,
                      "tags" : [
                        "PHP",
                        "Programming"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/todolist/{todolistId}": {
      "put": {
        "security": [
          {
            "TodolistAuth" : []
          }
        ],
        "tags": ["Todolist"],
        "summary": "Update existing todolist",
        "description": "Update todolist in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/TodolistId"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name" : {
                    "type": "string",
                    "minLength": 1,
                    "required": true
                  },
                  "priority" : {
                    "type": "integer",
                    "format": "int32",
                    "required": true,
                    "default": 1
                  },
                  "tags" : {
                    "type": "array",
                    "required": true,
                    "minItems": 1,
                    "items": {
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              },
              "examples": {
                "golang" : {
                  "description": "Example update todolistId Golang",
                  "value": {
                    "name" : "Golang",
                    "priority": 1,
                    "tags" : [
                      "Golang",
                      "Programming"
                    ]
                  }
                },
                "php" : {
                  "description": "Example update todolistId PHP",
                  "value": {
                    "name" : "PHP",
                    "priority": 2,
                    "tags" : [
                      "PHP",
                      "Programming"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update todolist",
            "content": {
              "application/json" : {
                "schema": {
                  "type": "array",
                  "properties": {
                    "id" : {
                      "type": "string"
                    },
                    "name" : {
                      "type": "string"
                    },
                    "priority" : {
                      "type": "number",
                      "format": "int32"
                    },
                    "tags" : {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "Golang" : {
                    "description": "Success update golang todolist",
                    "value":  {
                      "id" : "1",
                      "name" : "Golang",
                      "priority" : 2,
                      "tags" : [
                        "Golang",
                        "Programming"
                      ]
                    }
                  },
                  "PHP" : {
                    "description": "Success update php todolist",
                    "value": {
                      "id" : "2",
                      "name" : "PHP",
                      "priority" : 6,
                      "tags" : [
                        "PHP",
                        "Programming"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "TodolistAuth" : []
          }
        ],
        "tags": ["Todolist"],
        "summary": "Delete Existing todolist",
        "description": "Update todolist in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/TodolistId"
          }

        ],
        "responses": {
          "200": {
            "description": "Success delete todolist",
            "content": {
              "application/json" : {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success" : {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "success" : {
                    "description": "Success delete todolist",
                    "value": {
                      "success" : true
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Failed delete not found todolist",
            "content": {
              "application/json" : {
                "schema": {
                  "type": "object",
                  "properties": {
                    "failed" : {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "failed" : {
                    "description": "Failed delete todolist",
                    "value": {
                      "failed" : false
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "TodolistAuth" : {
        "description": "Authentication for todolist RESTful API",
        "type": "apiKey",
        "in": "header",
        "name": "X-API-KEY"
      }
    },
    "parameters": {
      "TodolistId" : {
        "name": "todolistId",
        "in": "path",
        "required": true,
        "description": "TodolistId for updated",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        },
        "examples": {
          "Golang" : {
            "description": "Sample todolistId for Golang",
            "value": 1
          },
          "PHP" : {
            "description": "Sample todolistId for PHP",
            "value": 2
          }
        }
      }
    },
    "schemas": {
      "Todolist" : {
        "type": "object",
        "properties": {
          "id" : {
            "type": "string"
          },
          "name" : {
            "type": "string"
          },
          "priority" : {
            "type": "number",
            "format": "int32"
          },
          "tags" : {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "CreateOrUpdateTodolist" : {
        "type": "object",
        "properties": {
          "name" : {
            "type": "string",
            "minLength": 1,
            "required": true
          },
          "priority" : {
            "type": "integer",
            "required": true,
            "minLength": 1,
            "default": 1,
            "format": "int32"
          },
          "tags" : {
            "type": "array",
            "required": true,
            "minLength": 1,
            "items": {
              "type": "string"
            }
          }
        }
      },
      "ArrayTodolist" : {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Todolist"
        }
      }
    }
  }
}